name: indice_concurrencia
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas
  - geopandas
  - folium
  - matplotlib
  - seaborn
  - numpy
  - shapely
  - jupyter
  - scipy
  - osmnx
  - pip:
    - overturemaps
